[package]
name = "driver_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
spatial_led = "0.2"
ratatui = { version = "0.29", features = ["crossterm"] }
crossterm = { version = "0.28" }
rand = { version = "0.8", default-features = false, features = [
    "std",
    "std_rng",
] }
